CREATE TABLE IF NOT EXISTS runs (
 source TEXT NOT NULL, tick INTEGER NOT NULL, PRIMARY KEY(source,tick)
);
CREATE TABLE IF NOT EXISTS snapshots (
 source TEXT NOT NULL, ts INTEGER NOT NULL, data TEXT NOT NULL,
 PRIMARY KEY(source,ts)
);
CREATE TABLE IF NOT EXISTS state (
 source TEXT PRIMARY KEY, ts INTEGER NOT NULL, cooldown TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS signals (
 source TEXT NOT NULL, ts INTEGER NOT NULL, data TEXT NOT NULL,
 PRIMARY KEY(source,ts)
);
CREATE TABLE IF NOT EXISTS budget (
 month TEXT PRIMARY KEY, used INTEGER NOT NULL DEFAULT 0
);
