import crypto from 'node:crypto';
import http from 'node:http';
import {createDB} from '../railway/db.mjs';
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const fetchJSON=async(url)=>{const r=await fetch(url,{headers:{accept:'application/json','user-agent':'crypto-monitor-agent/2.0'},signal:AbortSignal.timeout(10000)});if(!r.ok)throw new Error('http_'+r.status);return r.json();};
const safe=async(source,url,project=x=>x)=>{const at=new Date().toISOString();try{return {source,url,observedAt:at,status:'ok',data:project(await fetchJSON(url))};}catch(e){return {source,url,observedAt:at,status:'unavailable',error:String(e.message||e)};}};
const mean=a=>a.reduce((s,x)=>s+x,0)/Math.max(1,a.length),ema=(a,n)=>{let v=a[0]||0,k=2/(n+1);for(const x of a.slice(1))v=x*k+v*(1-k);return v;};
export function rsi(a,n=14){if(a.length<n+1)return 50;let g=0,l=0;for(let i=a.length-n;i<a.length;i++){let d=a[i]-a[i-1];d>0?g+=d:l-=d;}return l?100-100/(1+(g/n)/(l/n)):100;}
export function atr(c,n=14){const x=c.slice(-n);return mean(x.map((v,i)=>i?Math.max(v.h-v.l,Math.abs(v.h-x[i-1].c),Math.abs(v.l-x[i-1].c)):v.h-v.l));}
export function technical(c){const a=c.map(x=>x.c),last=a.at(-1),e9=ema(a.slice(-40),9),e21=ema(a.slice(-60),21),rr=rsi(a),aa=atr(c),ret6=(last/a.at(-7)-1)*1e4;let score=(e9>e21?1:-1)+(rr>55?1:rr<45?-1:0)+(ret6>20?1:ret6<-20?-1:0);return {last,ema9:e9,ema21:e21,rsi:rr,atr:aa,ret30mBps:ret6,score};}
export function fuse({technical=0,derivatives=0,macro=0,onchain=0,fundamental=0,news=0}){const scores={technical,derivatives,macro,onchain,fundamental,news};const total=Object.values(scores).reduce((a,b)=>a+b,0),action=total>=2?'LONG':total<=-2?'SHORT':'NO_TRADE';return {action,score:total,confidence:Math.min(.78,.5+Math.abs(total)*.05),scores};}
export function ablations(scores){const full=fuse(scores);return Object.fromEntries(Object.keys(scores).map(k=>[k,{without:fuse({...scores,[k]:0}).action,deltaScore:scores[k]}]).concat([['FULL',full]]));}
async function candles(){const x=await fetchJSON('https://api.exchange.coinbase.com/products/BTC-USD/candles?granularity=300');return x.sort((a,b)=>a[0]-b[0]).slice(-100).map(v=>({t:v[0],l:+v[1],h:+v[2],o:+v[3],c:+v[4],v:+v[5]}));}
async function evidence(t){
 const [fund,global,fees,macro,news]=await Promise.all([
  safe('binance-usdm','https://fapi.binance.com/fapi/v1/premiumIndex?symbol=BTCUSDT',x=>({fundingRate:+x.lastFundingRate,markPrice:+x.markPrice})),
  safe('coingecko','https://api.coingecko.com/api/v3/global',x=>({btcDominance:x.data?.market_cap_percentage?.btc,totalMarketCap:x.data?.total_market_cap?.usd,marketCapChange24h:x.data?.market_cap_change_percentage_24h_usd})),
  safe('mempool.space','https://mempool.space/api/v1/fees/recommended',x=>x),
  safe('alternative.me','https://api.alternative.me/fng/?limit=1',x=>({fearGreed:+x.data?.[0]?.value,label:x.data?.[0]?.value_classification})),
  safe('coindesk-rss-proxy','https://api.rss2json.com/v1/api.json?rss_url=https%3A%2F%2Fwww.coindesk.com%2Farc%2Foutboundfeeds%2Frss%2F',x=>({titles:(x.items||[]).slice(0,5).map(i=>i.title)}))
 ]);
 const d=fund.status==='ok'?(fund.data.fundingRate>0.0005?-.5:fund.data.fundingRate<-.0005?.5:0):0;
 const m=macro.status==='ok'?(macro.data.fearGreed>=75?-.25:macro.data.fearGreed<=25?.25:0):0;
 const o=fees.status==='ok'?(fees.data.fastestFee>=50?-.25:0):0;
 const f=global.status==='ok'?(global.data.marketCapChange24h>2?.25:global.data.marketCapChange24h<-2?-.25:0):0;
 return {raw:{derivatives:fund,fundamental:global,onchain:fees,macro,news},scores:{technical:t.score,derivatives:d,macro:m,onchain:o,fundamental:f,news:0}};
}
async function schema(db){await db.exec(`CREATE TABLE IF NOT EXISTS agent_signals(signal_id text PRIMARY KEY,created_at bigint NOT NULL,symbol text NOT NULL,horizon_minutes int NOT NULL,action text NOT NULL CHECK(action IN ('LONG','SHORT','NO_TRADE')),entry_price double precision NOT NULL,evidence_json text NOT NULL,model_version text NOT NULL,evidence_hash text NOT NULL UNIQUE);CREATE TABLE IF NOT EXISTS agent_outcomes(signal_id text NOT NULL REFERENCES agent_signals(signal_id),due_at bigint NOT NULL,evaluated_at bigint,exit_price double precision,return_bps double precision,PRIMARY KEY(signal_id));CREATE TABLE IF NOT EXISTS agent_ablations(signal_id text PRIMARY KEY REFERENCES agent_signals(signal_id),ablation_json text NOT NULL);CREATE OR REPLACE FUNCTION agent_signal_immutable() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'agent_signals immutable'; END $$;DROP TRIGGER IF EXISTS agent_signals_no_mutation ON agent_signals;CREATE TRIGGER agent_signals_no_mutation BEFORE UPDATE OR DELETE ON agent_signals FOR EACH ROW EXECUTE FUNCTION agent_signal_immutable();`);}
const hash=x=>crypto.createHash('sha256').update(JSON.stringify(x)).digest('hex');
async function settle(db,now){const q=await db.prepare('SELECT o.signal_id,s.action,s.entry_price FROM agent_outcomes o JOIN agent_signals s USING(signal_id) WHERE o.evaluated_at IS NULL AND o.due_at<=?').bind(now).all();if(!(q.results||[]).length)return;const p=(await candles()).at(-1).c;for(const x of q.results){const d=x.action==='LONG'?1:x.action==='SHORT'?-1:0;await db.prepare('UPDATE agent_outcomes SET evaluated_at=?,exit_price=?,return_bps=? WHERE signal_id=? AND evaluated_at IS NULL').bind(now,p,d*(p/+x.entry_price-1)*1e4,x.signal_id).run();}}
export async function runOnce(db=createDB(),now=Date.now()){await schema(db);await settle(db,now);const c=await candles(),t=technical(c),e=await evidence(t),decision=fuse(e.scores),abl=ablations(e.scores);const ev={observedAt:new Date(now).toISOString(),technical:t,...e.raw,scores:e.scores,decision,ablations:abl};const id='agent-'+crypto.randomUUID(),eh=hash(ev);await db.prepare('INSERT INTO agent_signals VALUES (?,?,?,?,?,?,?,?,?)').bind(id,now,'BTCUSDT',240,decision.action,t.last,JSON.stringify(ev),'signal-agent-v2',eh).run();await db.prepare('INSERT INTO agent_outcomes(signal_id,due_at) VALUES (?,?)').bind(id,now+14400000).run();await db.prepare('INSERT INTO agent_ablations VALUES (?,?)').bind(id,JSON.stringify(abl)).run();console.log(JSON.stringify({checkpoint:'AGENT_DECISION_WRITTEN',signal_id:id,action:decision.action,entry:t.last,confidence:decision.confidence,scores:e.scores,evidence_hash:eh}));return {id,...decision,entry:t.last,evidence:ev};}
async function dashboard(db){const q=await db.prepare('SELECT s.signal_id,s.created_at,s.action,s.entry_price,s.evidence_json,s.model_version,o.evaluated_at,o.exit_price,o.return_bps,a.ablation_json FROM agent_signals s LEFT JOIN agent_outcomes o USING(signal_id) LEFT JOIN agent_ablations a USING(signal_id) ORDER BY s.created_at DESC LIMIT 50').all();return q.results||[];}
function serve(db){const port=+(process.env.PORT||3000);http.createServer(async(req,res)=>{if(req.url==='/api/state'){res.setHeader('content-type','application/json');return res.end(JSON.stringify(await dashboard(db)));}if(req.url==='/health')return res.end('ok');res.setHeader('content-type','text/html; charset=utf-8');res.end(`<!doctype html><meta name=viewport content="width=device-width"><title>Crypto Agent Live</title><style>body{font:14px system-ui;background:#0b0d10;color:#e8eaed;margin:24px}h1{font-size:22px}.card{border:1px solid #30363d;border-radius:12px;padding:14px;margin:10px 0}.LONG{border-color:#238636}.SHORT{border-color:#da3633}.muted{color:#8b949e}pre{white-space:pre-wrap}</style><h1>Crypto Agent · Live</h1><div class=muted>auto refresh 15s · prospective ledger</div><main id=a>loading…</main><script>async function r(){let x=await fetch('/api/state').then(r=>r.json());a.innerHTML=x.map(v=>'<div class="card '+v.action+'"><b>'+v.action+'</b> · BTCUSDT @ '+Number(v.entry_price).toFixed(2)+'<br><span class=muted>'+new Date(+v.created_at).toLocaleString()+' · '+v.model_version+' · '+v.signal_id+'</span><pre>'+JSON.stringify(JSON.parse(v.evidence_json).scores,null,2)+'</pre>'+(v.evaluated_at?'<b>Outcome: '+Number(v.return_bps).toFixed(1)+' bps</b>':'Outcome: pending')+'</div>').join('')}r();setInterval(r,15000)</script>`);}).listen(port,()=>console.log(JSON.stringify({checkpoint:'DASHBOARD_LISTENING',port})));}
if(import.meta.url===`file://${process.argv[1]}`){const db=createDB();serve(db);for(;;){try{await runOnce(db);}catch(e){console.error(JSON.stringify({checkpoint:'AGENT_ERROR',error:String(e.message||e)}));}await sleep(+(process.env.AGENT_INTERVAL_MS||300000));}}
