import crypto from 'node:crypto';
import {createDB} from '../railway/db.mjs';

const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const j=async u=>{const r=await fetch(u,{headers:{accept:'application/json','user-agent':'crypto-monitor-agent/1.0'},signal:AbortSignal.timeout(10000)});if(!r.ok)throw new Error('http_'+r.status);return r.json();};
const mean=a=>a.reduce((s,x)=>s+x,0)/Math.max(1,a.length);
const ema=(a,n)=>{if(!a.length)return 0;const k=2/(n+1);let v=a[0];for(const x of a.slice(1))v=x*k+v*(1-k);return v;};
export function rsi(a,n=14){if(a.length<n+1)return 50;let g=0,l=0;for(let i=a.length-n;i<a.length;i++){const d=a[i]-a[i-1];if(d>0)g+=d;else l-=d;}if(!l)return 100;const rs=(g/n)/(l/n);return 100-100/(1+rs);}
export function atr(c,n=14){const x=c.slice(-n);return mean(x.map((v,i)=>i?Math.max(v.h-v.l,Math.abs(v.h-x[i-1].c),Math.abs(v.l-x[i-1].c)):v.h-v.l));}
export function technical(c){const close=c.map(x=>x.c),last=close.at(-1),e9=ema(close.slice(-40),9),e21=ema(close.slice(-60),21),rr=rsi(close),aa=atr(c),ret1=(last/close.at(-2)-1)*10000,ret6=(last/close.at(-7)-1)*10000;let score=0;score+=e9>e21?1:-1;score+=rr>55?1:rr<45?-1:0;score+=ret6>20?1:ret6<-20?-1:0;return {last,ema9:e9,ema21:e21,rsi:rr,atr:aa,ret1Bps:ret1,ret30mBps:ret6,score};}
export function fuse({tech,derivatives={}}){let s=tech.score;const f=Number(derivatives.fundingRate);if(Number.isFinite(f))s+=f>0.0005?-0.5:f<-0.0005?0.5:0;const action=s>=2?'LONG':s<=-2?'SHORT':'NO_TRADE';const confidence=Math.min(.75,.5+Math.abs(s)*.05);return {action,score:s,confidence};}
async function candles(){const raw=await j('https://api.exchange.coinbase.com/products/BTC-USD/candles?granularity=300');return raw.slice().sort((a,b)=>a[0]-b[0]).slice(-100).map(x=>({t:x[0],l:Number(x[1]),h:Number(x[2]),o:Number(x[3]),c:Number(x[4]),v:Number(x[5])}));}
async function derivatives(){try{const x=await j('https://fapi.binance.com/fapi/v1/premiumIndex?symbol=BTCUSDT');return {source:'binance-usdm',fundingRate:Number(x.lastFundingRate),markPrice:Number(x.markPrice)};}catch(e){return {source:'unavailable',error:String(e.message||e)};}}
async function schema(db){await db.exec(`CREATE TABLE IF NOT EXISTS agent_signals(signal_id text PRIMARY KEY,created_at bigint NOT NULL,symbol text NOT NULL,horizon_minutes int NOT NULL,action text NOT NULL CHECK(action IN ('LONG','SHORT','NO_TRADE')),entry_price double precision NOT NULL,evidence_json text NOT NULL,model_version text NOT NULL,evidence_hash text NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS agent_outcomes(signal_id text NOT NULL REFERENCES agent_signals(signal_id),due_at bigint NOT NULL,evaluated_at bigint,exit_price double precision,return_bps double precision,PRIMARY KEY(signal_id));
CREATE OR REPLACE FUNCTION agent_signal_immutable() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'agent_signals immutable'; END $$;
DROP TRIGGER IF EXISTS agent_signals_no_mutation ON agent_signals;CREATE TRIGGER agent_signals_no_mutation BEFORE UPDATE OR DELETE ON agent_signals FOR EACH ROW EXECUTE FUNCTION agent_signal_immutable();`);}
async function telegram(text){const token=process.env.TELEGRAM_BOT_TOKEN,chat=process.env.TELEGRAM_CHAT_ID;if(!token||!chat)return false;const r=await fetch('https://api.telegram.org/bot'+token+'/sendMessage',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({chat_id:chat,text})});if(!r.ok)throw new Error('telegram_'+r.status);return true;}
const hash=x=>crypto.createHash('sha256').update(JSON.stringify(x)).digest('hex');
async function settle(db,now){const q=await db.prepare('SELECT o.signal_id,s.action,s.entry_price FROM agent_outcomes o JOIN agent_signals s USING(signal_id) WHERE o.evaluated_at IS NULL AND o.due_at<=?').bind(now).all();if(!(q.results||[]).length)return 0;const p=(await candles()).at(-1).c;for(const x of q.results){const d=x.action==='LONG'?1:x.action==='SHORT'?-1:0;const b=d*(p/Number(x.entry_price)-1)*10000;await db.prepare('UPDATE agent_outcomes SET evaluated_at=?,exit_price=?,return_bps=? WHERE signal_id=? AND evaluated_at IS NULL').bind(now,p,b,x.signal_id).run();}return q.results.length;}
export async function runOnce(db=createDB(),now=Date.now()){await schema(db);await settle(db,now);const [c,d]=await Promise.all([candles(),derivatives()]);const t=technical(c),decision=fuse({tech:t,derivatives:d});const evidence={observedAt:new Date(now).toISOString(),technical:t,derivatives:d,decision};const id='agent-'+crypto.randomUUID(),eh=hash(evidence);await db.prepare('INSERT INTO agent_signals(signal_id,created_at,symbol,horizon_minutes,action,entry_price,evidence_json,model_version,evidence_hash) VALUES (?,?,?,?,?,?,?,?,?)').bind(id,now,'BTCUSDT',240,decision.action,t.last,JSON.stringify(evidence),'signal-agent-v1',eh).run();await db.prepare('INSERT INTO agent_outcomes(signal_id,due_at) VALUES (?,?)').bind(id,now+240*60000).run();console.log(JSON.stringify({checkpoint:'AGENT_DECISION_WRITTEN',signal_id:id,action:decision.action,entry:t.last,confidence:decision.confidence,evidence_hash:eh}));if(decision.action!=='NO_TRADE'){const stop=decision.action==='LONG'?t.last-1.5*t.atr:t.last+1.5*t.atr;const tp=decision.action==='LONG'?t.last+3*t.atr:t.last-3*t.atr;await telegram(['BTCUSDT | '+decision.action+' | 4H','Entry: '+t.last.toFixed(2),'Invalidation: '+stop.toFixed(2),'Target: '+tp.toFixed(2),'R:R ≈ 2.0','Confidence: '+(decision.confidence*100).toFixed(0)+'% (uncalibrated v1)','Technical score: '+t.score,'Funding: '+(Number.isFinite(d.fundingRate)?d.fundingRate:'unavailable'),'Signal ID: '+id].join('\n'));}return {id,...decision,entry:t.last,evidence};}
if(import.meta.url===`file://${process.argv[1]}`){const db=createDB();for(;;){try{await runOnce(db);}catch(e){console.error(JSON.stringify({checkpoint:'AGENT_ERROR',error:String(e.message||e)}));}await sleep(Number(process.env.AGENT_INTERVAL_MS||300000));}}
