const fmt=x=>x==null?"—":typeof x==="number"?x.toLocaleString(undefined,{maximumFractionDigits:2}):x;
async function state(){try{const r=await fetch(process.env.AGENT_STATE_URL||"https://crypto-monitor-production-33be.up.railway.app/api/state",{cache:"no-store"});if(!r.ok)throw new Error("upstream "+r.status);return {ok:true,data:await r.json()}}catch(e){return {ok:false,error:String(e)}}}
const Card=({title,children,wide=""})=><article className={"card "+wide}><div className="cardTitle">{title}</div>{children}</article>;
export default async function Page(){const s=await state(),d=s.data||{},sig=d.signal||d.latestSignal||d.latest||{},ev=sig.evidence||d.evidence||{},scores=sig.scores||{};const action=sig.action||d.action||"UNKNOWN";const horizons=d.horizons||{};const regime=d.regime||{};return <main>
<header><div className="brand"><i>✦</i><div><b>CRYPTO MONITOR AI</b><small>MARKET INTELLIGENCE · AGENTIC TRADING · REAL EVIDENCE</small></div></div><div className={"pill "+(s.ok?"good":"bad")}>{s.ok?"● LIVE · PRODUCTION":"● DEGRADED"}</div></header>
<section className="ticker"><div><span>BTC</span><b>{sig.entry?"$"+fmt(+sig.entry):"LIVE"}</b></div><div><span>ACTION</span><b className={action==="SHORT"?"short":action==="LONG"?"long":""}>{action}</b></div><div><span>HORIZON</span><b>{sig.horizon||"4h"}</b></div><div><span>MODEL</span><b>{sig.model_version||"production"}</b></div></section>
<section className="layout"><Card title="LATEST SIGNAL" wide="signal"><div className="signalTop"><h1>{action}</h1><div><small>Entry</small><strong>{sig.entry?"$"+fmt(+sig.entry):"—"}</strong></div></div><div className="kv"><span>Probability</span><b>{sig.calibrated_probability??"UNCALIBRATED"}</b><span>Raw score</span><b>{sig.confidence??sig.decisionStrength??"—"}</b><span>Observed</span><b>{sig.observed_at||sig.created_at||d.timestamp||"—"}</b><span>ID</span><code>{sig.signal_id||sig.id||"—"}</code></div></Card>
<Card title="EXECUTION GEOMETRY"><div className="kv"><span>Entry zone</span><b>{sig.entry_zone||"—"}</b><span>Invalidation</span><b>{sig.invalidation||"—"}</b><span>Targets</span><b>{Array.isArray(sig.targets)?sig.targets.join(" · "):(sig.targets||"—")}</b><span>Net edge</span><b>{sig.net_edge_bps!=null?sig.net_edge_bps+" bps":"—"}</b></div></Card>
<Card title="REGIME POSTERIOR"><div className="big">{regime.label||sig.regime||"UNKNOWN"}</div><div className="bars">{Object.entries(regime.probabilities||{}).map(([k,v])=><div key={k}><span>{k}</span><i style={{width:(100*v)+"%"}}/><b>{fmt(v)}</b></div>)}</div></Card>
<Card title="MULTI-HORIZON DISTRIBUTION"><table><thead><tr><th>H</th><th>P↓</th><th>P↑</th><th>Move</th><th>MAE</th></tr></thead><tbody>{["15m","1h","4h","24h"].map(h=>{const x=horizons[h]||{};return <tr key={h}><td>{h}</td><td>{fmt(x.pDown)}</td><td>{fmt(x.pUp)}</td><td>{x.expectedMoveBps!=null?x.expectedMoveBps+"bp":"—"}</td><td>{x.maeBps!=null?x.maeBps+"bp":"—"}</td></tr>})}</tbody></table></Card>
<Card title="LIVE EVIDENCE" wide="evidence">{["technical","microstructure","derivatives","cross_market","onchain","macro","news"].map(k=><div className="evidenceRow" key={k}><span>{k.replace("_"," ")}</span><b>{ev[k]??scores[k]??"—"}</b><small>{sig.freshness?.[k]??""}</small></div>)}</Card>
<Card title="CAUSAL CONTRIBUTIONS"><div className="agents">{Object.entries(d.agentContributions||scores).map(([k,v])=><div key={k}><span>{k}</span><i><em style={{width:Math.min(100,Math.abs(Number(v)||0)*100)+"%"}}/></i><b>{fmt(v)}</b></div>)}</div></Card>
<Card title="PROVENANCE / DATA HEALTH"><div className="kv"><span>Source</span><b>{sig.source||d.source||"—"}</b><span>Evidence hash</span><code>{sig.evidence_hash||"—"}</code><span>Freshness</span><b>{sig.freshness_status||"—"}</b><span>OOD</span><b>{sig.ood??"—"}</b></div></Card>
</section>{!s.ok&&<section className="error"><b>UPSTREAM DEGRADED</b><p>{s.error}</p><p>No stale state is presented as live.</p></section>}
<footer><span>DISCIPLINE CREATES FREEDOM</span><span>WORLD → SENSORS → STATE → AGENTS → OPPORTUNITY → OUTCOME → ABLATION</span></footer></main>}